[tool.pdm]
version = { source = "file", path = "src/tvm_book/__about__.py" }
allow_prereleases = true
[tool.pdm.dev-dependencies]


[project]
name = "tvm-book"
dynamic = ["version"]
authors = [
    {name = "xinetzone", email = "xinzone@outlook.com"},
]
dependencies = [
    "importlib-metadata>=4.12",
    # "tvmx @ file:///${PROJECT_ROOT}/../tvm/xinetzone",
]
requires-python = ">=3.10"
readme = "README.md"
license = {file = "LICENSE"}

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[project.urls]
Homepage = "https://xinetzone.github.io/tvm-book"
Repository = "https://github.com/xinetzone/tvm-book"
Documentation = "https://xinetzone.github.io/tvm-book"

# [project.entry-points]
# "sphinx.html_themes" = {tvm_book = "tvm_book"}

[project.optional-dependencies]
doc = [
  "sphinx>4",
  "myst-nb",
  "xyzstyle",
  "matplotlib",
  "sphinx-copybutton",
  "sphinxcontrib-bibtex",
  "sphinx-thebe",
  "sphinx-design",
  "sphinx-automodapi",
  "sphinx-sitemap",
  "sphinx_plotly_directive",
  "sphinx-comments",
  "sphinxcontrib-mermaid",
  "plotly",
  "sphinxcontrib-websupport"
]

[tool.pdm.build]
# package-dir = "src"
# includes = []
excludes = ["doc", ".github"]
source-includes = ["tests/"]
